version: '3.1'
services:

  db:
    image: postgres:13.2
    env_file:
      - database.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mosquitto:
    image: eclipse-mosquitto:1.6.13
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - mosquitto-conf:/mosquitto/config
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  backend:
    image: backend
    volumes:
      - ./backend:/app
    build:
      context: backend
    depends_on:
      - db
    ports:
      - 80:80
    command: bash -c "sleep 5 && /start-reload.sh"
    env_file:
      - backend.env
      - database.env

  streamlit:
    build: frontend
    command: "streamlit run main.py"
    ports:
      - "8501:8501"
    volumes:
      - "./frontend:/usr/src/app"
    env_file:
      - frontend.env
    depends_on:
      - db
      - backend
    links:
      - backend

volumes:
  pgdata:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
